//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ksenia
        ///Mariya
        ///Marina
        ///Anastasia
        ///Elizaveta
        ///Lyubov
        ///Vladlena
        ///Valentina
        ///Anna
        ///Janna
        ///Valeria
        ///Antonina
        ///Rose.
        /// </summary>
        internal static string FemaleFirstNames {
            get {
                return ResourceManager.GetString("FemaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volodina
        ///Putina
        ///Sazonova
        ///Kazbeeva
        ///Jdanova
        ///Petrova
        ///Ivanova
        ///Andreychenko
        ///Jidova
        ///Ivleeva
        ///Evtushenko
        ///Prokhorova
        ///Vainshtein.
        /// </summary>
        internal static string FemaleLastNames {
            get {
                return ResourceManager.GetString("FemaleLastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexsandr
        ///Alexey
        ///Anton
        ///Andrey
        ///Arkadiy
        ///Vladimir
        ///Vasiliy
        ///Gennadiy
        ///Dmitriy
        ///Sergey
        ///Maxim
        ///Valeriy
        ///Roman.
        /// </summary>
        internal static string MaleFirstNames {
            get {
                return ResourceManager.GetString("MaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volodin
        ///Putin
        ///Sazonov
        ///Kazbeev
        ///Jdanov
        ///Petrov
        ///Ivanov
        ///Andreychenko
        ///Jidov
        ///Ivleev
        ///Evtushenko
        ///Prokhorov
        ///Vainshtein.
        /// </summary>
        internal static string MaleLastNames {
            get {
                return ResourceManager.GetString("MaleLastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married
        ///NotMarried
        ///Divorced
        ///Widower.
        /// </summary>
        internal static string Marriage {
            get {
                return ResourceManager.GetString("Marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant
        ///Builder
        ///Cashier 
        ///Cook
        ///Designer
        ///Doctor
        ///Driver
        ///Engineer
        ///Fireman
        ///Hairdresser
        ///Journalist
        ///Judge
        ///Lawyer
        ///Locksmith
        ///Marketer
        ///Mechanic
        ///Nurse
        ///Photographer
        ///Plumber
        ///Policeman
        ///Taxi driver
        ///Teacher
        ///Translator
        ///Welder
        ///Unemployed.
        /// </summary>
        internal static string NameOfWork {
            get {
                return ResourceManager.GetString("NameOfWork", resourceCulture);
            }
        }
    }
}
